# Generated by Django 4.2.7 on 2025-02-24 21:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('address', models.CharField(default='', max_length=255)),
                ('place_of_birth', models.CharField(default='', max_length=255)),
                ('marital_status', models.CharField(default='', max_length=50)),
                ('state_of_origin', models.CharField(default='', max_length=50)),
                ('local_govt_origin', models.CharField(default='', max_length=50)),
                ('ward', models.CharField(default='', max_length=10)),
                ('permanent_address', models.CharField(default='', max_length=255)),
                ('village', models.CharField(default='', max_length=255)),
                ('whatsapp_tel', models.CharField(default='', max_length=20)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('dob', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('country_birth', models.CharField(default='', max_length=100)),
                ('institution_type', models.CharField(default='', max_length=100)),
                ('course_name', models.CharField(default='', max_length=255)),
                ('institution', models.CharField(default='', max_length=255)),
                ('course_duration', models.CharField(default='', max_length=50)),
                ('inst_address', models.CharField(default='', max_length=255)),
                ('portal_link', models.CharField(default='', max_length=255)),
                ('matric_no', models.CharField(default='', max_length=50)),
                ('portal_username', models.CharField(default='', max_length=100)),
                ('portal_password', models.CharField(default='', max_length=100)),
                ('commencement', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('completion', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('councilor', models.CharField(default='', max_length=255)),
                ('education', models.JSONField(blank=True, null=True)),
                ('declaration', models.BooleanField(default=False)),
                ('support_docs', models.FileField(blank=True, null=True, upload_to='support_docs/')),
                ('id_card', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='admission_letters/')),
                ('academic_result', models.FileField(blank=True, null=True, upload_to='academic_results/')),
                ('nabwes_receipt', models.FileField(blank=True, null=True, upload_to='nabwes_receipts/')),
                ('radio_tv_license', models.FileField(blank=True, null=True, upload_to='radio_tv_licenses/')),
                ('letter_of_oba', models.FileField(blank=True, null=True, upload_to='letter_of_oba/')),
                ('origin_certificate', models.FileField(blank=True, null=True, upload_to='origin_certificates/')),
                ('document', models.FileField(blank=True, null=True, upload_to='bursary_documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ict_cleared', 'Cleared by ICT'), ('council_reviewed', 'Reviewed by Councilors'), ('hod_approved', 'HOD Approved'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ICT', 'ICT Department'), ('Councilors', 'Councilors'), ('HOD', 'HOD'), ('Chairman', 'Chairman'), ('Final', 'Final Remark')], max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bursary.bursaryapplication')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
