# Generated by Django 4.2.7 on 2025-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryapplication',
            name='reference_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
