# Generated by Django 4.2.7 on 2025-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('ICT', 'ICT Officer'), ('COUNCILOR', 'Councilor'), ('HOD', 'Head of Department'), ('CHAIRMAN', 'Chairman')], default='APPLICANT', max_length=20),
        ),
    ]
