# Generated by Django 4.2.7 on 2025-02-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('ICT', 'ICT Officer'), ('COUNCILOR', 'Councilor'), ('HOD', 'Head of Department'), ('CHAIRMAN', 'Chairman')], default='user', max_length=20),
        ),
    ]
