# Generated by Django 4.2.7 on 2024-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='website_or_social_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
