# Generated by Django 4.2.7 on 2024-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_sponsor_website_or_social_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscried_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
