# Generated by Django 4.2.7 on 2024-12-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_subsscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsscriber',
            new_name='Subscriber',
        ),
    ]
