# Generated by Django 4.2.7 on 2025-01-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_due_remove_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='due',
            old_name='due_name',
            new_name='name',
        ),
    ]
