# Generated by Django 4.2.7 on 2025-01-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_rename_due_name_due_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.due'),
        ),
    ]
