# Generated by Django 4.2.7 on 2025-02-28 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
