# on:
#   push:
#     branches:
#       - master

# name: Deploy Django Project to cPanel

# jobs:
#   web-deploy:
#     name: Deploy Django Project
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the code
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       # Step 2: Install Python and dependencies
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.12.0"

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 3: Collect static files
#       - name: Collect Static Files
#         env:
#           DJANGO_SETTINGS_MODULE: nabwes.settings
#         run: |
#           python manage.py collectstatic --noinput

#       # Step 4: Sync files to cPanel via FTP
#       - name: Deploy to cPanel via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#         with:
#           server: ${{ secrets.NABWES_FTP_SEVER }}
#           username: ${{ secrets.NABWES_FTP_USER }}
#           password: ${{ secrets.NABWES_FTP_PASSWORD }}
#           local-dir: ./
#           exclude: |
#             .git*
#             *.md
#             requirements.txt
#             venv/
#             __pycache__/
#             .github/
#             .env

#       # Step 5: Notify on success
#       - name: Deployment Success
#         run: echo "Deployment to cPanel was successful!"

name: Deploy Django Project to cPanel via SSH

on:
  push:
    branches:
      - master # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: ssh-keyscan -p 1624 -H nabwes.com.ng >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -p 1624 -o StrictHostKeyChecking=no essioilo@nabwes.com.ng <<EOF
            echo "Connected to server on port 1624"
            cd /home/essioilo/west
            git pull origin master
            cd  /home/essioilo/west  
            /home/essioilo/virtualenv/west/3.11/bin/pip install -r requirements.txt
            /home/essioilo/virtualenv/west/3.11/bin/python manage.py migrate
            /home/essioilo/virtualenv/west/3.11/bin/python manage.py collectstatic --noinput
            touch /home/essioilo/west/restart.txt  # Trigger server restart (e.g., with Passenger)
            echo "Testig " > restart.txt
          EOF
